### ISSUE TITLE
surprised by directory naming

### ISSUE THREAD

**Issue by jspaaks** [tortellini-tools/action#69]
1. I was surprised to see a directory named `dist/` checked into the repo. (Why) is this correct behavior?
2. The `npm run build` creates a directory `lib/`, is this what we want? It suggests checked-in dependencies to me (like jars in a Java project). I'd expect a `build/` or a `_build/`.
3. `__tests__/`, I'm guessing this is ordained by `jest`, but I still find it surprising to not simply have `test/` or `tests/`.

**Comment by sverhoeven** [comment]
This is the layout the https://github.com/actions/typescript-action template gave us, it works but is a bit surprising.

Because Typescript needs to be compiled (libs) and dependencies must be bundled using ncc (dist) before the action can be run without having to install/compile/bundle JS files.
There is https://github.com/actions/typescript-action/issues/283 that suggest a simplification.

Indeed `__tests__` is the default for jest, see https://jestjs.io/docs/configuration#testmatch-arraystring

**Comment by sverhoeven** [comment]
@jspaaks answer was good enough
